name: Fairy

on:
  schedule:
    - cron: '0 12 * * *' # every day at noon
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runner's shell
      - name: Run commit script
        run: |
           git config --global user.name "${GITHUB_ACTOR}"
           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
           git commit --allow-empty -m "Plant grass: $(date +'%Y-%m-%d %H:%M:%S')" 
           git push origin master
